### ISSUE TITLE
`modify_metadata`: Missing `error_message` property in `failed_operation` property

### ISSUE THREAD

**Issue by sam-i-am012** [irods/irods_client_http_api#294] opened 2024-07-09 16:21 UTC
- [x] main
- [x] 4-3-stable
---
## Documentation
Referring to the collections endpoint, the documentation includes a `failed_operation` stanza but is missing the `error_message` property. 
```
{
    "irods_response": {
        "status_code": 0
        "status_message": "string", // Optional
        "failed_operation": {
            "operation": {
                "operation": "string", // add or remove.
                "attribute": "string",
                "value": "string",
                "units": "string" // Optional.
            },
            "operation_index": 0,
            "status_message": "string"
        }
    }
}
```

When doing the `modify_metadata` request, I received this JSON string 
```
{
  "irods_response" : {
    "failed_operation" : {
      "operation" : {
        "attribute" : "test",
        "operation" : "add",
        "units" : "null",
        "value" : "test1"
      },
      "error_message" : "[json.exception.out_of_range.403] key 'acl' not found"
    },
    "status_code" : -154000
  }
}
```

**Comment by trel** [comment] 2024-07-09 16:27
is it `failed_operation` or `failed_response`?

**Comment by korydraughn** [comment] 2024-07-09 16:59
Aside from the docs needing a tweak, I'm surprised to see `acl` in the error_message property.

Will verify whether that's correct.

**Comment by trel** [comment] 2024-07-09 17:00
very good.

**Comment by korydraughn** [comment] 2024-07-11 17:24
Confirmed the mention of `key 'acl' not found` was because the metadata payload was passed to the `modify_permissions` endpoint operation.

Everything is working as intended. Closing now that the docs have been corrected.

**Closed by korydraughn** 2024-07-11 17:24 UTC
Labels: documentation
