### ISSUE TITLE
Seems write op doesn't trigger all peps needed 

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#190] opened 2023-12-22 16:50 UTC
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
By writing I wanted to trigger peps possibly needed.

### Expected behavior
I expected to see `pep_api_replica_open_*`, `pep_api_data_obj_write_*` and `pep_api_replica_close_*` would have been triggered.

### Observed behavior (including steps to reproduce, if applicable)
Only `pep_api_replica_open_*` was triggered with the operation below;

```
[irods@dev-u0137480 go-http-client]$ time curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' -F  'op=write' -F 'lpath=/u0137480/home/rods/myfile.txt' -F 'count=7' -F 'bytes=abcdfg'
{"irods_response":{"status_code":0}}
real    0m0.084s
user    0m0.004s
sys     0m0.004s
```

Note: I see some inconsistencies as well. Hard to observer and report. They were mostly;

- Some time I didnt see any pep triggered,
- Depending on my write size and client used peps above were triggered.

That is why I put only one client example above. I am sure the issue can be reproduced with my example.

**Comment by trel** [comment] 2023-12-22 17:24
I would have expected replica_open and replica_close to be triggered, perhaps among others.

**Comment by korydraughn** [comment] 2023-12-22 21:39
I tried this manually and all PEPs fired as expected. I think things are working as intended.

Q. Could other policy be getting in the way of your test?
Q. Was `myfile.txt` created and does it contain the data you passed?

I want to point out the size of the string passed to `bytes` does not match the value passed to `count`.

**Comment by mstfdkmn** [comment] 2023-12-22 21:52
Very strange! Now all are triggered. But I am very sure sometime they are not triggered. Perhaps related to #186?

> I want to point out the size of the string passed to bytes does not match the value passed to count.

Does this matter? Asking because I used that in some of my test with curl.

**Comment by korydraughn** [comment] 2023-12-22 22:17
> Perhaps related to #186?

Hard to say.

> Does this matter? Asking because I used that in some of my test with curl.

For 0.1.0, yes. At the moment, the HTTP API is trusting you're passing the correct value to `count`. We'll get that fixed for the next release though. If you pass a value larger than what's available, there's no telling what the outcome will be. The HTTP API could attempt to read memory that doesn't belong to it.

**Comment by korydraughn** [comment] 2023-12-22 22:24
> Perhaps related to #186?

I'll add that the mismatch `count` and `bytes` params could be the reason behind the weird behavior.

**Comment by korydraughn** [comment] 2024-01-10 21:53
I think this is resolved by #194.

With that resolved, there's no known way to write more bytes than what's available.

**Comment by trel** [comment] 2024-01-11 00:58
Okay - @mstfdkmn please weigh in.  But we'll probably close this for 0.2.0.    Any new issues can be opened after that.

**Comment by mstfdkmn** [comment] 2024-01-11 10:06
Okay this can be now closed and open a new one if encountered again. We need to test this with the next release. As I stated, in some circumstance those were not triggered. I guess when I made the servers busy enough, PEPs were not triggered but if the servers were fresh or had no activity for some time, they were triggered. But this is just an assumption (supported by my observation) - meaning not happened always.

**Closed** 2024-01-11 13:34 UTC
Labels: consortium-member
